// Copyright 2026 The OpenSandbox Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
	sandboxv1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/client/clientset/versioned/typed/sandbox/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeBatchSandboxes implements BatchSandboxInterface
type fakeBatchSandboxes struct {
	*gentype.FakeClientWithList[*v1alpha1.BatchSandbox, *v1alpha1.BatchSandboxList]
	Fake *FakeSandboxV1alpha1
}

func newFakeBatchSandboxes(fake *FakeSandboxV1alpha1, namespace string) sandboxv1alpha1.BatchSandboxInterface {
	return &fakeBatchSandboxes{
		gentype.NewFakeClientWithList[*v1alpha1.BatchSandbox, *v1alpha1.BatchSandboxList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("batchsandboxes"),
			v1alpha1.SchemeGroupVersion.WithKind("BatchSandbox"),
			func() *v1alpha1.BatchSandbox { return &v1alpha1.BatchSandbox{} },
			func() *v1alpha1.BatchSandboxList { return &v1alpha1.BatchSandboxList{} },
			func(dst, src *v1alpha1.BatchSandboxList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.BatchSandboxList) []*v1alpha1.BatchSandbox {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.BatchSandboxList, items []*v1alpha1.BatchSandbox) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
