package scheduler

// Code generated by MockGen. DO NOT EDIT.
// Source: internal/scheduler/default_scheduler.go

// Package mock_scheduler is a generated GoMock package.

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	api "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/task-executor"
)

// MocktaskClient is a mock of taskClient interface.
type MocktaskClient struct {
	ctrl     *gomock.Controller
	recorder *MocktaskClientMockRecorder
}

// MocktaskClientMockRecorder is the mock recorder for MocktaskClient.
type MocktaskClientMockRecorder struct {
	mock *MocktaskClient
}

// NewMocktaskClient creates a new mock instance.
func NewMocktaskClient(ctrl *gomock.Controller) *MocktaskClient {
	mock := &MocktaskClient{ctrl: ctrl}
	mock.recorder = &MocktaskClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskClient) EXPECT() *MocktaskClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocktaskClient) Get(ctx context.Context) (*api.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*api.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocktaskClientMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocktaskClient)(nil).Get), ctx)
}

// Set mocks base method.
func (m *MocktaskClient) Set(ctx context.Context, task *api.Task) (*api.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, task)
	ret0, _ := ret[0].(*api.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MocktaskClientMockRecorder) Set(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MocktaskClient)(nil).Set), ctx, task)
}
