// Code generated by MockGen. DO NOT EDIT.
// Source: internal/scheduler/status_collector.go

// Package scheduler is a generated GoMock package.
package scheduler

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	api "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/task-executor"
)

// MocktaskStatusCollector is a mock of taskStatusCollector interface.
type MocktaskStatusCollector struct {
	ctrl     *gomock.Controller
	recorder *MocktaskStatusCollectorMockRecorder
}

// MocktaskStatusCollectorMockRecorder is the mock recorder for MocktaskStatusCollector.
type MocktaskStatusCollectorMockRecorder struct {
	mock *MocktaskStatusCollector
}

// NewMocktaskStatusCollector creates a new mock instance.
func NewMocktaskStatusCollector(ctrl *gomock.Controller) *MocktaskStatusCollector {
	mock := &MocktaskStatusCollector{ctrl: ctrl}
	mock.recorder = &MocktaskStatusCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskStatusCollector) EXPECT() *MocktaskStatusCollectorMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MocktaskStatusCollector) Collect(ctx context.Context, ipList []string) (map[string]*api.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, ipList)
	ret0, _ := ret[0].(map[string]*api.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MocktaskStatusCollectorMockRecorder) Collect(ctx, ipList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MocktaskStatusCollector)(nil).Collect), ctx, ipList)
}
