#
# Copyright 2025 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
Sandbox model converter utilities.

Provides conversion functions between API models and domain models,
similar to the Kotlin SDK SandboxModelConverter.

This converter is designed to work with openapi-python-client generated models,
which use attrs for model definitions.
"""
from datetime import datetime, timedelta, timezone
from typing import Literal, cast

from opensandbox.api.lifecycle.models import (
    CreateSandboxResponse,
    Endpoint,
    ListSandboxesResponse,
    ListSnapshotsResponse,
    RenewSandboxExpirationRequest,
    RenewSandboxExpirationResponse,
    Sandbox,
    Snapshot,
)
from opensandbox.api.lifecycle.models import (
    CreateSnapshotRequest as ApiCreateSnapshotRequest,
)
from opensandbox.api.lifecycle.models import (
    PaginationInfo as ApiPaginationInfo,
)
from opensandbox.api.lifecycle.models import (
    SandboxStatus as ApiSandboxStatus,
)
from opensandbox.api.lifecycle.models.create_sandbox_request import CreateSandboxRequest
from opensandbox.api.lifecycle.models.image_spec import ImageSpec
from opensandbox.api.lifecycle.types import Unset
from opensandbox.models.sandboxes import (
    CreateSnapshotRequest,
    CredentialProxyConfig,
    NetworkPolicy,
    NetworkRule,
    PagedSandboxInfos,
    PagedSnapshotInfos,
    PaginationInfo,
    PlatformSpec,
    SandboxCreateResponse,
    SandboxEndpoint,
    SandboxImageSpec,
    SandboxInfo,
    SandboxLifecycle,
    SandboxRenewResponse,
    SandboxStatus,
    SnapshotInfo,
    SnapshotStatus,
    Volume,
)


class SandboxModelConverter:
    """
    Sandbox model converter utilities.

    Provides static methods to convert between API models and domain models,
    following the pattern from the Kotlin SDK.

    The API models are generated by openapi-python-client and use attrs,
    while domain models are standard Python dataclasses/classes.
    """

    @staticmethod
    def _additional_properties_to_dict(value: object) -> dict[str, str] | None:
        if isinstance(value, Unset):
            return None
        if hasattr(value, "additional_properties"):
            props = getattr(value, "additional_properties", None)
            if isinstance(props, dict):
                return dict(props)
        if isinstance(value, dict):
            return value
        return None

    @staticmethod
    def to_api_image_spec(spec: SandboxImageSpec) -> ImageSpec:
        """Convert domain SandboxImageSpec to API ImageSpec."""
        from opensandbox.api.lifecycle.models.image_spec import ImageSpec
        from opensandbox.api.lifecycle.models.image_spec_auth import ImageSpecAuth
        from opensandbox.api.lifecycle.types import UNSET

        auth = UNSET
        if spec.auth:
            auth = ImageSpecAuth(
                username=spec.auth.username,
                password=spec.auth.password,
            )

        return ImageSpec(
            uri=spec.image,  # API uses 'uri', domain uses 'image'
            auth=auth,
        )

    @staticmethod
    def to_api_volume(volume: Volume):
        """Convert domain Volume to API Volume."""
        from opensandbox.api.lifecycle.models.host import (
            Host as ApiHost,
        )
        from opensandbox.api.lifecycle.models.ossfs import (
            OSSFS as ApiOSSFS,
        )
        from opensandbox.api.lifecycle.models.ossfs_version import OSSFSVersion
        from opensandbox.api.lifecycle.models.pvc import (
            PVC as ApiPVC,
        )
        from opensandbox.api.lifecycle.models.volume import Volume as ApiVolume
        from opensandbox.api.lifecycle.types import UNSET

        api_host = UNSET
        if volume.host is not None and not isinstance(volume.host, Unset):
            api_host = ApiHost(path=volume.host.path)

        api_pvc = UNSET
        if volume.pvc is not None and not isinstance(volume.pvc, Unset):
            api_pvc = ApiPVC(
                claim_name=volume.pvc.claim_name,
                create_if_not_exists=volume.pvc.create_if_not_exists,
                delete_on_sandbox_termination=volume.pvc.delete_on_sandbox_termination,
                storage_class=volume.pvc.storage_class,
                storage=volume.pvc.storage,
                access_modes=volume.pvc.access_modes,
            )

        api_ossfs = UNSET
        if (
            volume.ossfs is not None
            and not isinstance(volume.ossfs, Unset)
            and volume.ossfs.access_key_id is not None
            and volume.ossfs.access_key_secret is not None
        ):
            api_ossfs = ApiOSSFS(
                bucket=volume.ossfs.bucket,
                endpoint=volume.ossfs.endpoint,
                access_key_id=volume.ossfs.access_key_id,
                access_key_secret=volume.ossfs.access_key_secret,
                version=OSSFSVersion(volume.ossfs.version),
                options=volume.ossfs.options if volume.ossfs.options is not None else UNSET,
            )

        api_sub_path = UNSET
        if volume.sub_path is not None and not isinstance(volume.sub_path, Unset):
            api_sub_path = volume.sub_path

        return ApiVolume(
            name=volume.name,
            mount_path=volume.mount_path,
            read_only=volume.read_only,
            host=api_host,
            pvc=api_pvc,
            ossfs=api_ossfs,
            sub_path=api_sub_path,
        )

    @staticmethod
    def to_api_create_sandbox_request(
        spec: SandboxImageSpec | None,
        entrypoint: list[str] | None,
        env: dict[str, str],
        metadata: dict[str, str],
        timeout: timedelta | None,
        resource: dict[str, str],
        platform: PlatformSpec | None,
        network_policy: NetworkPolicy | None,
        extensions: dict[str, str],
        volumes: list[Volume] | None,
        secure_access: bool = False,
        snapshot_id: str | None = None,
        credential_proxy: CredentialProxyConfig | None = None,
        resource_requests: dict[str, str] | None = None,
        lifecycle: SandboxLifecycle | None = None,
    ) -> CreateSandboxRequest:
        """Convert domain parameters to API CreateSandboxRequest."""
        from opensandbox.api.lifecycle.models.create_sandbox_request import (
            CreateSandboxRequest,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_env import (
            CreateSandboxRequestEnv,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_extensions import (
            CreateSandboxRequestExtensions,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_metadata import (
            CreateSandboxRequestMetadata,
        )
        from opensandbox.api.lifecycle.models.credential_proxy_config import (
            CredentialProxyConfig as ApiCredentialProxyConfig,
        )
        from opensandbox.api.lifecycle.models.platform_spec import (
            PlatformSpec as ApiPlatformSpec,
        )
        from opensandbox.api.lifecycle.models.resource_limits import ResourceLimits
        from opensandbox.api.lifecycle.models.sandbox_lifecycle import (
            SandboxLifecycle as ApiSandboxLifecycle,
        )
        from opensandbox.api.lifecycle.types import UNSET

        # Convert env dict to API model
        api_env = UNSET
        if env:
            api_env = CreateSandboxRequestEnv.from_dict(env)

        # Convert metadata dict to API model
        api_metadata = UNSET
        if metadata:
            api_metadata = CreateSandboxRequestMetadata.from_dict(metadata)

        # Convert resource limits dict to API model
        api_resource_limits = ResourceLimits.from_dict(resource)

        api_network_policy = SandboxModelConverter.to_api_network_policy(
            network_policy
        )

        api_credential_proxy = UNSET
        if credential_proxy is not None:
            if not isinstance(credential_proxy, CredentialProxyConfig):
                raise TypeError(
                    "credential_proxy must be a CredentialProxyConfig or None, "
                    f"got {type(credential_proxy).__name__}"
                )
            api_credential_proxy = ApiCredentialProxyConfig(
                enabled=credential_proxy.enabled,
            )

        api_extensions = (
            CreateSandboxRequestExtensions.from_dict(extensions) if extensions else UNSET
        )

        api_platform = UNSET
        if platform is not None:
            # Use from_dict to support both string-backed and enum-backed
            # generated PlatformSpec models across generator versions.
            api_platform = ApiPlatformSpec.from_dict(
                {
                    "os": platform.os,
                    "arch": platform.arch,
                }
            )

        api_lifecycle = UNSET
        if lifecycle is not None:
            if not isinstance(lifecycle, SandboxLifecycle):
                raise TypeError(
                    "lifecycle must be a SandboxLifecycle or None, "
                    f"got {type(lifecycle).__name__}"
                )
            if lifecycle.pre_start is not None or lifecycle.periodic:
                lifecycle_payload = lifecycle.model_dump(
                    by_alias=True, exclude_none=True
                )
                if not lifecycle_payload.get("periodic"):
                    lifecycle_payload.pop("periodic", None)
                api_lifecycle = ApiSandboxLifecycle.from_dict(lifecycle_payload)

        # Convert volumes to API model
        api_volumes = UNSET
        if volumes is not None and len(volumes) > 0:
            api_volumes = [
                SandboxModelConverter.to_api_volume(v) for v in volumes
            ]

        image = (
            SandboxModelConverter.to_api_image_spec(spec)
            if spec is not None
            else UNSET
        )
        api_resource_requests = UNSET
        if resource_requests:
            api_resource_requests = ResourceLimits.from_dict(resource_requests)

        request = CreateSandboxRequest(
            image=image,
            snapshot_id=snapshot_id if snapshot_id is not None else UNSET,
            entrypoint=entrypoint if entrypoint is not None else UNSET,
            env=api_env,
            metadata=api_metadata,
            lifecycle=api_lifecycle,
            resource_limits=api_resource_limits,
            resource_requests=api_resource_requests,
            platform=api_platform,
            network_policy=api_network_policy,
            credential_proxy=api_credential_proxy,
            extensions=api_extensions,
            volumes=api_volumes,
            secure_access=secure_access,
        )
        if timeout is None:
            # Preserve an explicit manual-cleanup request as JSON null.
            request.timeout = None
        else:
            request.timeout = int(timeout.total_seconds())
        return request

    @staticmethod
    def to_api_network_policy(
        network_policy: NetworkPolicy | None,
    ):
        """Convert domain NetworkPolicy to the generated API model (UNSET when None)."""
        from opensandbox.api.lifecycle.models.network_policy import (
            NetworkPolicy as ApiNetworkPolicy,
        )
        from opensandbox.api.lifecycle.models.network_policy_default_action import (
            NetworkPolicyDefaultAction,
        )
        from opensandbox.api.lifecycle.models.network_rule import (
            NetworkRule as ApiNetworkRule,
        )
        from opensandbox.api.lifecycle.models.network_rule_action import (
            NetworkRuleAction,
        )
        from opensandbox.api.lifecycle.types import UNSET

        if network_policy is None:
            return UNSET
        if not isinstance(network_policy, NetworkPolicy):
            raise TypeError(
                "network_policy must be a NetworkPolicy or None, "
                f"got {type(network_policy).__name__}"
            )

        api_default_action = UNSET
        if network_policy.default_action:
            api_default_action = NetworkPolicyDefaultAction(
                network_policy.default_action
            )

        api_egress = UNSET
        if network_policy.egress is not None:
            api_egress = [
                ApiNetworkRule(
                    action=NetworkRuleAction(rule.action),
                    target=rule.target,
                )
                for rule in network_policy.egress
            ]

        return ApiNetworkPolicy(
            default_action=api_default_action,
            egress=api_egress,
        )

    @staticmethod
    def to_api_create_template_sandbox_request(
        template_id: str,
        timeout: timedelta,
        metadata: dict[str, str] | None,
        network_policy: NetworkPolicy | None,
        extensions: dict[str, str] | None,
    ) -> CreateSandboxRequest:
        """Convert template-mode parameters to API CreateSandboxRequest.

        Template mode fixes the workload shape on the server: workload-shaping
        fields (entrypoint, env, resources, volumes, platform, ...) must be
        omitted or the server rejects the request with 400.
        """
        from opensandbox.api.lifecycle.models.create_sandbox_request_extensions import (
            CreateSandboxRequestExtensions,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_metadata import (
            CreateSandboxRequestMetadata,
        )
        from opensandbox.api.lifecycle.types import UNSET

        request = CreateSandboxRequest(
            template_id=template_id,
            metadata=(
                CreateSandboxRequestMetadata.from_dict(metadata)
                if metadata
                else UNSET
            ),
            network_policy=SandboxModelConverter.to_api_network_policy(
                network_policy
            ),
            extensions=(
                CreateSandboxRequestExtensions.from_dict(extensions)
                if extensions
                else UNSET
            ),
        )
        request.timeout = int(timeout.total_seconds())
        return request

    @staticmethod
    def to_api_create_snapshot_request(
        request: CreateSnapshotRequest | None,
    ) -> ApiCreateSnapshotRequest:
        from opensandbox.api.lifecycle.types import UNSET

        if request is None:
            return ApiCreateSnapshotRequest()
        return ApiCreateSnapshotRequest(
            name=request.name if request.name is not None else UNSET
        )

    @staticmethod
    def to_api_renew_request(
        new_expiration_time: datetime,
    ) -> RenewSandboxExpirationRequest:
        """Convert datetime to API renew request."""
        from opensandbox.api.lifecycle.models.renew_sandbox_expiration_request import (
            RenewSandboxExpirationRequest,
        )

        # Ensure timezone-aware datetime for unambiguous serialization.
        # If a naive datetime is provided, treat it as UTC.
        if new_expiration_time.tzinfo is None:
            new_expiration_time = new_expiration_time.replace(tzinfo=timezone.utc)

        return RenewSandboxExpirationRequest(
            expires_at=new_expiration_time,
        )

    @staticmethod
    def to_api_network_rules(rules: list[NetworkRule]):
        """Convert domain NetworkRule list to API NetworkRule list."""
        from opensandbox.api.lifecycle.models.network_rule import (
            NetworkRule as ApiNetworkRule,
        )
        from opensandbox.api.lifecycle.models.network_rule_action import (
            NetworkRuleAction,
        )

        return [
            ApiNetworkRule(
                action=NetworkRuleAction(rule.action),
                target=rule.target,
            )
            for rule in rules
        ]

    @staticmethod
    def to_sandbox_network_policy(api_policy):
        """Convert API NetworkPolicy to domain NetworkPolicy."""
        from opensandbox.api.lifecycle.models.network_policy import (
            NetworkPolicy as ApiNetworkPolicy,
        )
        from opensandbox.api.lifecycle.types import Unset

        if not isinstance(api_policy, ApiNetworkPolicy):
            raise TypeError(f"Expected NetworkPolicy, got {type(api_policy).__name__}")

        default_action: str | None = "deny"
        if not isinstance(api_policy.default_action, Unset):
            default_action = cast(
                Literal["allow", "deny"],
                getattr(api_policy.default_action, "value", api_policy.default_action),
            )

        egress: list[NetworkRule] | None = None
        if not isinstance(api_policy.egress, Unset):
            egress = [
                NetworkRule(
                    action=cast(
                        Literal["allow", "deny"],
                        getattr(rule.action, "value", rule.action),
                    ),
                    target=rule.target,
                )
                for rule in api_policy.egress
            ]

        return NetworkPolicy.model_validate(
            {
                "defaultAction": default_action,
                "egress": egress,
            }
        )

    @staticmethod
    def to_sandbox_renew_response(
        api_response: RenewSandboxExpirationResponse,
    ) -> SandboxRenewResponse:
        """
        Convert API RenewSandboxExpirationResponse to domain SandboxRenewResponse.

        Note: We intentionally keep the public SDK surface using domain models instead of the
        generated OpenAPI client models.
        """

        if not isinstance(api_response, RenewSandboxExpirationResponse):
            raise TypeError(
                f"Expected RenewSandboxExpirationResponse, got {type(api_response).__name__}"
            )

        return SandboxRenewResponse(expires_at=api_response.expires_at)

    @staticmethod
    def to_sandbox_create_response(
        api_response: CreateSandboxResponse,
    ) -> SandboxCreateResponse:
        """Convert API CreateSandboxResponse to domain SandboxCreateResponse."""
        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import SandboxCreateResponse

        platform: PlatformSpec | None = None
        if hasattr(api_response, "platform") and not isinstance(api_response.platform, Unset):
            platform = PlatformSpec.model_validate(
                {
                    "os": str(getattr(api_response.platform.os, "value", api_response.platform.os)),
                    "arch": str(getattr(api_response.platform.arch, "value", api_response.platform.arch)),
                }
            )

        return SandboxCreateResponse(
            id=str(api_response.id),
            platform=platform,
            extensions=SandboxModelConverter._additional_properties_to_dict(
                getattr(api_response, "extensions", None)
            ),
        )

    @staticmethod
    def to_sandbox_info(api_sandbox: Sandbox) -> SandboxInfo:
        """Convert API Sandbox to domain SandboxInfo."""
        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import (
            SandboxAllocation,
            SandboxImageAuth,
            SandboxImageSpec,
            SandboxInfo,
        )

        domain_image_spec = None
        if hasattr(api_sandbox, "image") and not isinstance(api_sandbox.image, Unset):
            auth = None
            if hasattr(api_sandbox.image, "auth") and not isinstance(
                api_sandbox.image.auth, Unset
            ):
                auth_obj = api_sandbox.image.auth
                username_val = getattr(auth_obj, "username", None)
                password_val = getattr(auth_obj, "password", None)
                if isinstance(username_val, str) and isinstance(password_val, str):
                    auth = SandboxImageAuth(username=username_val, password=password_val)
            domain_image_spec = SandboxImageSpec(
                image=api_sandbox.image.uri,
                auth=auth,
            )

        metadata = (
            SandboxModelConverter._additional_properties_to_dict(
                getattr(api_sandbox, "metadata", None)
            )
            or {}
        )
        extensions = SandboxModelConverter._additional_properties_to_dict(
            getattr(api_sandbox, "extensions", None)
        )

        expires_at = api_sandbox.expires_at
        if isinstance(expires_at, Unset):
            expires_at = None

        platform: PlatformSpec | None = None
        if hasattr(api_sandbox, "platform") and not isinstance(api_sandbox.platform, Unset):
            platform = PlatformSpec.model_validate(
                {
                    "os": str(getattr(api_sandbox.platform.os, "value", api_sandbox.platform.os)),
                    "arch": str(getattr(api_sandbox.platform.arch, "value", api_sandbox.platform.arch)),
                }
            )

        allocation: SandboxAllocation | None = None
        api_allocation = getattr(api_sandbox, "allocation", None)
        if not isinstance(api_allocation, Unset) and api_allocation is not None:
            allocation = SandboxAllocation(
                mode=cast(
                    Literal["pool"],
                    str(getattr(api_allocation.mode, "value", api_allocation.mode)),
                ),
                pool_ref=api_allocation.pool_ref,
                state=cast(
                    Literal["allocated"],
                    str(getattr(api_allocation.state, "value", api_allocation.state)),
                ),
            )

        return SandboxInfo(
            id=api_sandbox.id,
            status=SandboxModelConverter._convert_sandbox_status(api_sandbox.status),
            image=domain_image_spec,
            snapshot_id=(
                None
                if isinstance(getattr(api_sandbox, "snapshot_id", None), Unset)
                else getattr(api_sandbox, "snapshot_id", None)
            ),
            platform=platform,
            allocation=allocation,
            created_at=api_sandbox.created_at,
            expires_at=expires_at,
            entrypoint=api_sandbox.entrypoint,
            metadata=metadata,
            extensions=extensions,
        )

    @staticmethod
    def to_snapshot_info(api_snapshot: Snapshot) -> SnapshotInfo:
        from opensandbox.api.lifecycle.types import Unset

        last_transition_at = api_snapshot.status.last_transition_at
        if isinstance(last_transition_at, Unset):
            last_transition_at = None

        reason = api_snapshot.status.reason
        if isinstance(reason, Unset):
            reason = None

        message = api_snapshot.status.message
        if isinstance(message, Unset):
            message = None

        name = api_snapshot.name
        if isinstance(name, Unset):
            name = None

        return SnapshotInfo(
            id=api_snapshot.id,
            sandbox_id=api_snapshot.sandbox_id,
            name=name,
            status=SnapshotStatus(
                state=api_snapshot.status.state,
                reason=reason,
                message=message,
                last_transition_at=last_transition_at,
            ),
            created_at=api_snapshot.created_at,
        )

    @staticmethod
    def to_paged_sandbox_infos(
        api_response: ListSandboxesResponse,
    ) -> PagedSandboxInfos:
        """Convert API ListSandboxesResponse to domain PagedSandboxInfos."""
        from opensandbox.models.sandboxes import PagedSandboxInfos

        items = api_response.items if hasattr(api_response, "items") else []

        return PagedSandboxInfos(
            sandbox_infos=[SandboxModelConverter.to_sandbox_info(s) for s in items],
            pagination=SandboxModelConverter._convert_pagination_info(
                api_response.pagination
            ),
        )

    @staticmethod
    def to_paged_snapshot_infos(
        api_response: ListSnapshotsResponse,
    ) -> PagedSnapshotInfos:
        items = api_response.items if hasattr(api_response, "items") else []

        return PagedSnapshotInfos(
            snapshot_infos=[SandboxModelConverter.to_snapshot_info(s) for s in items],
            pagination=SandboxModelConverter._convert_pagination_info(
                api_response.pagination
            ),
        )

    @staticmethod
    def to_sandbox_endpoint(
        api_endpoint: Endpoint, origin: str | None = None
    ) -> SandboxEndpoint:
        """Convert API Endpoint to domain SandboxEndpoint.

        ``origin`` carries the value of the OPEN-SANDBOX-ORIGIN response
        header when the server provides it.
        """
        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import SandboxEndpoint

        headers: dict[str, str] = {}
        if not isinstance(api_endpoint.headers, Unset):
            headers = dict(api_endpoint.headers.additional_properties)
        return SandboxEndpoint(
            endpoint=api_endpoint.endpoint,
            headers=headers,
            origin=origin,
        )

    @staticmethod
    def _convert_sandbox_status(
        api_status: ApiSandboxStatus | None,
    ) -> SandboxStatus:
        """Convert API SandboxStatus to domain SandboxStatus."""
        from datetime import datetime

        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import SandboxStatus

        if api_status is None:
            return SandboxStatus(
                state="Unknown",
                reason=None,
                message=None,
                last_transition_at=None,
            )

        reason: str | None = None
        if hasattr(api_status, "reason"):
            reason_val = api_status.reason
            if isinstance(reason_val, str):
                reason = reason_val

        message: str | None = None
        if hasattr(api_status, "message"):
            message_val = api_status.message
            if isinstance(message_val, str):
                message = message_val

        last_transition_at: datetime | None = None
        if hasattr(api_status, "last_transition_at"):
            lta_val = api_status.last_transition_at
            if isinstance(lta_val, datetime):
                last_transition_at = lta_val
            elif isinstance(lta_val, Unset) or lta_val is None:
                last_transition_at = None

        return SandboxStatus(
            state=api_status.state,
            reason=reason,
            message=message,
            last_transition_at=last_transition_at,
        )

    @staticmethod
    def _convert_pagination_info(
        api_pagination: ApiPaginationInfo | None,
    ) -> PaginationInfo:
        """Convert API PaginationInfo to domain PaginationInfo."""
        from opensandbox.models.sandboxes import PaginationInfo

        if api_pagination is None:
            return PaginationInfo(
                page=1,
                page_size=10,
                total_pages=0,
                total_items=0,
                has_next_page=False,
            )

        return PaginationInfo(
            page=api_pagination.page or 1,
            page_size=api_pagination.page_size or 10,
            total_pages=api_pagination.total_pages or 0,
            total_items=api_pagination.total_items or 0,
            has_next_page=api_pagination.has_next_page or False,
        )
