// Copyright 2026 The OpenSandbox Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	sandboxv1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
	scheme "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BatchSandboxesGetter has a method to return a BatchSandboxInterface.
// A group's client should implement this interface.
type BatchSandboxesGetter interface {
	BatchSandboxes(namespace string) BatchSandboxInterface
}

// BatchSandboxInterface has methods to work with BatchSandbox resources.
type BatchSandboxInterface interface {
	Create(ctx context.Context, batchSandbox *sandboxv1alpha1.BatchSandbox, opts v1.CreateOptions) (*sandboxv1alpha1.BatchSandbox, error)
	Update(ctx context.Context, batchSandbox *sandboxv1alpha1.BatchSandbox, opts v1.UpdateOptions) (*sandboxv1alpha1.BatchSandbox, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, batchSandbox *sandboxv1alpha1.BatchSandbox, opts v1.UpdateOptions) (*sandboxv1alpha1.BatchSandbox, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*sandboxv1alpha1.BatchSandbox, error)
	List(ctx context.Context, opts v1.ListOptions) (*sandboxv1alpha1.BatchSandboxList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *sandboxv1alpha1.BatchSandbox, err error)
	BatchSandboxExpansion
}

// batchSandboxes implements BatchSandboxInterface
type batchSandboxes struct {
	*gentype.ClientWithList[*sandboxv1alpha1.BatchSandbox, *sandboxv1alpha1.BatchSandboxList]
}

// newBatchSandboxes returns a BatchSandboxes
func newBatchSandboxes(c *SandboxV1alpha1Client, namespace string) *batchSandboxes {
	return &batchSandboxes{
		gentype.NewClientWithList[*sandboxv1alpha1.BatchSandbox, *sandboxv1alpha1.BatchSandboxList](
			"batchsandboxes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *sandboxv1alpha1.BatchSandbox { return &sandboxv1alpha1.BatchSandbox{} },
			func() *sandboxv1alpha1.BatchSandboxList { return &sandboxv1alpha1.BatchSandboxList{} },
		),
	}
}
