// Code generated by MockGen. DO NOT EDIT.
// Source: internal/scheduler/interface.go

// Package mock_scheduler is a generated GoMock package.
package mock_scheduler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"

	scheduler "github.com/alibaba/OpenSandbox/sandbox-k8s/internal/scheduler"
	api "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/task-executor"
)

// MockTaskScheduler is a mock of TaskScheduler interface.
type MockTaskScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockTaskSchedulerMockRecorder
}

// MockTaskSchedulerMockRecorder is the mock recorder for MockTaskScheduler.
type MockTaskSchedulerMockRecorder struct {
	mock *MockTaskScheduler
}

// NewMockTaskScheduler creates a new mock instance.
func NewMockTaskScheduler(ctrl *gomock.Controller) *MockTaskScheduler {
	mock := &MockTaskScheduler{ctrl: ctrl}
	mock.recorder = &MockTaskSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskScheduler) EXPECT() *MockTaskSchedulerMockRecorder {
	return m.recorder
}

// AddTasks mocks base method.
func (m *MockTaskScheduler) AddTasks(tasks []*api.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTasks", tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTasks indicates an expected call of AddTasks.
func (mr *MockTaskSchedulerMockRecorder) AddTasks(tasks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTasks", reflect.TypeOf((*MockTaskScheduler)(nil).AddTasks), tasks)
}

// ListTask mocks base method.
func (m *MockTaskScheduler) ListTask() []scheduler.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTask")
	ret0, _ := ret[0].([]scheduler.Task)
	return ret0
}

// ListTask indicates an expected call of ListTask.
func (mr *MockTaskSchedulerMockRecorder) ListTask() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTask", reflect.TypeOf((*MockTaskScheduler)(nil).ListTask))
}

// Schedule mocks base method.
func (m *MockTaskScheduler) Schedule() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule")
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockTaskSchedulerMockRecorder) Schedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockTaskScheduler)(nil).Schedule))
}

// StopTask mocks base method.
func (m *MockTaskScheduler) StopTask() []scheduler.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopTask")
	ret0, _ := ret[0].([]scheduler.Task)
	return ret0
}

// StopTask indicates an expected call of StopTask.
func (mr *MockTaskSchedulerMockRecorder) StopTask() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopTask", reflect.TypeOf((*MockTaskScheduler)(nil).StopTask))
}

// UpdatePods mocks base method.
func (m *MockTaskScheduler) UpdatePods(pod []*v1.Pod) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdatePods", pod)
}

// UpdatePods indicates an expected call of UpdatePods.
func (mr *MockTaskSchedulerMockRecorder) UpdatePods(pod interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePods", reflect.TypeOf((*MockTaskScheduler)(nil).UpdatePods), pod)
}
