// Code generated by MockGen. DO NOT EDIT.
// Source: internal/scheduler/types.go

// Package mock_scheduler is a generated GoMock package.
package mock_scheduler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	scheduler "github.com/alibaba/OpenSandbox/sandbox-k8s/internal/scheduler"
)

// MockTask is a mock of Task interface.
type MockTask struct {
	ctrl     *gomock.Controller
	recorder *MockTaskMockRecorder
}

// MockTaskMockRecorder is the mock recorder for MockTask.
type MockTaskMockRecorder struct {
	mock *MockTask
}

// NewMockTask creates a new mock instance.
func NewMockTask(ctrl *gomock.Controller) *MockTask {
	mock := &MockTask{ctrl: ctrl}
	mock.recorder = &MockTaskMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTask) EXPECT() *MockTaskMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockTask) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockTaskMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockTask)(nil).GetName))
}

// GetPodName mocks base method.
func (m *MockTask) GetPodName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPodName indicates an expected call of GetPodName.
func (mr *MockTaskMockRecorder) GetPodName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodName", reflect.TypeOf((*MockTask)(nil).GetPodName))
}

// GetState mocks base method.
func (m *MockTask) GetState() scheduler.TaskState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(scheduler.TaskState)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockTaskMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockTask)(nil).GetState))
}

// IsResourceReleased mocks base method.
func (m *MockTask) IsResourceReleased() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsResourceReleased")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsResourceReleased indicates an expected call of IsResourceReleased.
func (mr *MockTaskMockRecorder) IsResourceReleased() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsResourceReleased", reflect.TypeOf((*MockTask)(nil).IsResourceReleased))
}

// GetTerminatedMessage mocks base method.
func (m *MockTask) GetTerminatedMessage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTerminatedMessage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTerminatedMessage indicates an expected call of GetTerminatedMessage.
func (mr *MockTaskMockRecorder) GetTerminatedMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTerminatedMessage", reflect.TypeOf((*MockTask)(nil).GetTerminatedMessage))
}
