// Copyright 2026 The OpenSandbox Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	sandboxv1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BatchSandboxLister helps list BatchSandboxes.
// All objects returned here must be treated as read-only.
type BatchSandboxLister interface {
	// List lists all BatchSandboxes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sandboxv1alpha1.BatchSandbox, err error)
	// BatchSandboxes returns an object that can list and get BatchSandboxes.
	BatchSandboxes(namespace string) BatchSandboxNamespaceLister
	BatchSandboxListerExpansion
}

// batchSandboxLister implements the BatchSandboxLister interface.
type batchSandboxLister struct {
	listers.ResourceIndexer[*sandboxv1alpha1.BatchSandbox]
}

// NewBatchSandboxLister returns a new BatchSandboxLister.
func NewBatchSandboxLister(indexer cache.Indexer) BatchSandboxLister {
	return &batchSandboxLister{listers.New[*sandboxv1alpha1.BatchSandbox](indexer, sandboxv1alpha1.Resource("batchsandbox"))}
}

// BatchSandboxes returns an object that can list and get BatchSandboxes.
func (s *batchSandboxLister) BatchSandboxes(namespace string) BatchSandboxNamespaceLister {
	return batchSandboxNamespaceLister{listers.NewNamespaced[*sandboxv1alpha1.BatchSandbox](s.ResourceIndexer, namespace)}
}

// BatchSandboxNamespaceLister helps list and get BatchSandboxes.
// All objects returned here must be treated as read-only.
type BatchSandboxNamespaceLister interface {
	// List lists all BatchSandboxes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sandboxv1alpha1.BatchSandbox, err error)
	// Get retrieves the BatchSandbox from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*sandboxv1alpha1.BatchSandbox, error)
	BatchSandboxNamespaceListerExpansion
}

// batchSandboxNamespaceLister implements the BatchSandboxNamespaceLister
// interface.
type batchSandboxNamespaceLister struct {
	listers.ResourceIndexer[*sandboxv1alpha1.BatchSandbox]
}
