// Copyright 2026 The OpenSandbox Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	sandboxv1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PoolLister helps list Pools.
// All objects returned here must be treated as read-only.
type PoolLister interface {
	// List lists all Pools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sandboxv1alpha1.Pool, err error)
	// Pools returns an object that can list and get Pools.
	Pools(namespace string) PoolNamespaceLister
	PoolListerExpansion
}

// poolLister implements the PoolLister interface.
type poolLister struct {
	listers.ResourceIndexer[*sandboxv1alpha1.Pool]
}

// NewPoolLister returns a new PoolLister.
func NewPoolLister(indexer cache.Indexer) PoolLister {
	return &poolLister{listers.New[*sandboxv1alpha1.Pool](indexer, sandboxv1alpha1.Resource("pool"))}
}

// Pools returns an object that can list and get Pools.
func (s *poolLister) Pools(namespace string) PoolNamespaceLister {
	return poolNamespaceLister{listers.NewNamespaced[*sandboxv1alpha1.Pool](s.ResourceIndexer, namespace)}
}

// PoolNamespaceLister helps list and get Pools.
// All objects returned here must be treated as read-only.
type PoolNamespaceLister interface {
	// List lists all Pools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*sandboxv1alpha1.Pool, err error)
	// Get retrieves the Pool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*sandboxv1alpha1.Pool, error)
	PoolNamespaceListerExpansion
}

// poolNamespaceLister implements the PoolNamespaceLister
// interface.
type poolNamespaceLister struct {
	listers.ResourceIndexer[*sandboxv1alpha1.Pool]
}
