// Copyright 2026 The OpenSandbox Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apissandboxv1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
	versioned "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/client/informers/externalversions/internalinterfaces"
	sandboxv1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/pkg/client/listers/sandbox/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BatchSandboxInformer provides access to a shared informer and lister for
// BatchSandboxes.
type BatchSandboxInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() sandboxv1alpha1.BatchSandboxLister
}

type batchSandboxInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBatchSandboxInformer constructs a new informer for BatchSandbox type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBatchSandboxInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBatchSandboxInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBatchSandboxInformer constructs a new informer for BatchSandbox type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBatchSandboxInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SandboxV1alpha1().BatchSandboxes(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SandboxV1alpha1().BatchSandboxes(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SandboxV1alpha1().BatchSandboxes(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SandboxV1alpha1().BatchSandboxes(namespace).Watch(ctx, options)
			},
		},
		&apissandboxv1alpha1.BatchSandbox{},
		resyncPeriod,
		indexers,
	)
}

func (f *batchSandboxInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBatchSandboxInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *batchSandboxInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apissandboxv1alpha1.BatchSandbox{}, f.defaultInformer)
}

func (f *batchSandboxInformer) Lister() sandboxv1alpha1.BatchSandboxLister {
	return sandboxv1alpha1.NewBatchSandboxLister(f.Informer().GetIndexer())
}
