# Copyright 2026 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: opensandbox-server
description: OpenSandbox Lifecycle API server for sandbox creation and management
type: application
version: 0.1.0
appVersion: "0.2.2"
# execd bootstrap.sh installed to /opt/opensandbox (flattened from /opt/opensandbox/bin)

keywords:
  - sandbox
  - kubernetes
  - api
  - lifecycle
  - batchsandbox
  - ingress
  - gateway

home: https://github.com/opensandbox-group/OpenSandbox
sources:
  - https://github.com/opensandbox-group/OpenSandbox/tree/main/server
  - https://github.com/opensandbox-group/OpenSandbox/tree/main/components/ingress

maintainers:
  - name: OpenSandbox Team
    email: opensandbox@example.com

# Kubernetes version constraints
kubeVersion: ">=1.21.1-0"

annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
